<script setup lang="ts">
import { toRef } from 'vue';
import { useRule } from '@/composables/useRules';
import { KIND_CLASSES, type RuleKind } from '@/composables/rule-kinds';
import Breadcrumb from '@/components/layout/Breadcrumb.vue';

const props = defineProps<{ id: string }>();
const idRef = toRef(props, 'id');
const { rule, loading, error } = useRule(() => idRef.value);

const kindClass = (k: RuleKind): string => KIND_CLASSES[k];
</script>

<template>
  <div class="px-12 py-10 max-w-[1080px] relative z-10">
    <header class="border-b border-rule-strong pb-4 mb-8">
      <Breadcrumb
        :crumbs="[
          { label: 'overview', to: '/' },
          { label: 'rules', to: '/rules' },
          { label: rule?.name ?? 'Loading…', mono: !rule },
        ]"
        class="mb-3"
      />
      <div v-if="rule" class="flex flex-wrap items-baseline justify-between gap-4">
        <div>
          <p :class="['font-mono text-[11px] uppercase tracking-wider', kindClass(rule.kind)]">{{ rule.kind }}</p>
          <h1 class="text-[22px] font-medium text-ink mt-1">{{ rule.name }}</h1>
          <p v-if="rule.description" class="mt-2 text-[13px] text-ink-dim max-w-[68ch]">{{ rule.description }}</p>
        </div>
        <div class="flex items-baseline gap-4 font-mono text-[11px] text-ink-faint">
          <span>{{ rule.status.toLowerCase() }}</span>
          <span>{{ rule.source.replace(/_/g, ' ') }}</span>
        </div>
      </div>
    </header>

    <p v-if="loading && !rule" class="text-[13px] text-ink-dim">loading…</p>
    <p v-else-if="error" class="text-[13px] text-sev-crit">failed to load: {{ error.message }}</p>
    <p v-else-if="!rule" class="text-[13px] text-ink-dim">rule not found.</p>

    <template v-else>
      <!-- Counters -->
      <section class="mb-8 grid grid-cols-3 gap-4">
        <div class="border border-rule-strong rounded-md px-4 py-3">
          <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint">derived from artifacts</p>
          <p class="font-mono text-[20px] text-ink mt-1 tabular-nums">{{ rule.derivedFromArtifactCount }}</p>
        </div>
        <div class="border border-rule-strong rounded-md px-4 py-3">
          <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint">detects techniques</p>
          <p class="font-mono text-[20px] text-ink mt-1 tabular-nums">{{ rule.detectsTechniqueCount }}</p>
        </div>
        <div class="border border-rule-strong rounded-md px-4 py-3">
          <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint">generated by hunts</p>
          <p class="font-mono text-[20px] text-ink mt-1 tabular-nums">{{ rule.generatedByHuntCount }}</p>
        </div>
      </section>

      <!-- Tags -->
      <section v-if="rule.tags.length" class="mb-6">
        <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint mb-2">tags</p>
        <div class="flex flex-wrap gap-2">
          <span
            v-for="t in rule.tags"
            :key="t"
            class="inline-flex px-2 py-0.5 rounded-sm border border-rule-strong text-ink-dim font-mono text-[11px]"
          >{{ t }}</span>
        </div>
      </section>

      <!-- Rule body -->
      <section class="mb-8">
        <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint mb-2">content</p>
        <pre class="bg-surface border border-rule rounded-md p-4 font-mono text-[12px] text-ink overflow-x-auto whitespace-pre-wrap">{{ rule.content }}</pre>
      </section>

      <!-- Provenance -->
      <section v-if="rule.sourceRef" class="mb-8">
        <p class="font-mono text-[10px] uppercase tracking-wider text-ink-faint mb-2">source ref</p>
        <p class="font-mono text-[12px] text-ink-dim">{{ rule.sourceRef }}</p>
      </section>

      <footer class="border-t border-rule pt-4 font-mono text-[10px] text-ink-faint">
        created {{ rule.createdAt.slice(0, 10) }} · updated {{ rule.updatedAt.slice(0, 10) }}
      </footer>
    </template>
  </div>
</template>
